# Linear Algebra
* Matrix multiplication
* Transpose

In [2]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2],[3,4],[5,6]])

In [3]:
a #[2,3]

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
b #[3,2]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
np.dot(a,b) #[2,3][3,2]

array([[22, 28],
       [49, 64]])

In [7]:
np.dot(b,a) #[3,2][2,3]

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [8]:
a.T #[3,2]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# 