In [1]:
import numpy as np

In [2]:
np.zeros(shape=(3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
np.ones(shape=(3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
x=np.random.random(size=(3,4))
x

array([[0.29274513, 0.69944808, 0.83367812, 0.57665339],
       [0.3567506 , 0.08160721, 0.51190339, 0.89021132],
       [0.37235872, 0.08199388, 0.61226369, 0.71075208]])

# Masking

In [8]:
x<0.5

array([[ True, False, False, False],
       [ True,  True, False, False],
       [ True,  True, False, False]])

In [9]:
x[x<0.5]

array([0.29274513, 0.3567506 , 0.08160721, 0.37235872, 0.08199388])

In [13]:
y=np.arange(start=0, stop=12, step=1)
z=np.reshape(y,(3,-1))
z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
z[x<0.5]

array([0, 4, 5, 8, 9])

# Timing

In [24]:
%%timeit
x=np.random.random(size=(100))
x[x<0.5]

3.9 µs ± 66.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [25]:
%%timeit
x=np.random.random(size=(100))
y=[]
for i in x:
    if i<0.5:
        y.append(i)

21.7 µs ± 512 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
